import type { Product } from "@/lib/woocommerce-types";

export const mockPreOrders: Product[] = [
  {
    id: 900001,
    name: "Creality K3 Ultra",
    slug: "creality-k3-ultra-pre-order",
    permalink: "/pre-order/creality-k3-ultra",
    description: "Temporary demo pre-order product for the homepage section.",
    short_description: "High-speed flagship printer available for reservation.",
    price_html: "",
    prices: {
      price: "599000",
      regular_price: "599000",
      sale_price: "599000",
      currency_code: "KWD",
      currency_minor_unit: 3,
    },
    price: 599,
    regular_price: 599,
    sale_price: 599,
    formatted_price: "599.000 KWD",
    currency_code: "KWD",
    currency_symbol: "KWD",
    currency_minor_unit: 3,
    images: [
      {
        id: 900001,
        src: "/images/printers.jpg",
        alt: "Creality K3 Ultra",
        name: "Creality K3 Ultra",
      },
    ],
    attributes: [],
    categories: [],
    tags: [],
    meta_data: [],
    product_order_type: "pre_order",
    is_in_stock: false,
    stock_status: "outofstock",
    stock_quantity: 0,
    purchasable: true,
    average_rating: 0,
    review_count: 0,
    featured: false,
    related_ids: [],
  },
  {
    id: 900002,
    name: "Creality Falcon Laser X",
    slug: "creality-falcon-laser-x-pre-order",
    permalink: "/pre-order/creality-falcon-laser-x",
    description: "Temporary demo pre-order product for the homepage section.",
    short_description: "Upcoming laser system available for early reservations.",
    price_html: "",
    prices: {
      price: "799000",
      regular_price: "799000",
      sale_price: "799000",
      currency_code: "KWD",
      currency_minor_unit: 3,
    },
    price: 799,
    regular_price: 799,
    sale_price: 799,
    formatted_price: "799.000 KWD",
    currency_code: "KWD",
    currency_symbol: "KWD",
    currency_minor_unit: 3,
    images: [
      {
        id: 900002,
        src: "/images/materials.jpg",
        alt: "Creality Falcon Laser X",
        name: "Creality Falcon Laser X",
      },
    ],
    attributes: [],
    categories: [],
    tags: [],
    meta_data: [],
    product_order_type: "pre_order",
    is_in_stock: false,
    stock_status: "outofstock",
    stock_quantity: 0,
    purchasable: true,
    average_rating: 0,
    review_count: 0,
    featured: false,
    related_ids: [],
  },
];
